install:
- wget https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.0.4.linux-x64.tar.gz
- tar -zxvf grafana-5.0.4.linux-x64.tar.gz --strip-components=1

script:
  - whoami
  - pwd

deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  organization: gds-tech-ops
  space: sandbox
  on:
    branch: master
    repo: alphagov/grafana-paas
  username:
    secure: aLWgDAxyN8rT0lDnAc1RRCjkKfLug7QKcc4pIs/N3qO9G9v9UAMgQSxCGqK0BAyXR6p0175DhHoJzWyanEnFfdw+YFgdWX888+Nq5sWcWLCXmskxiNXpvvAmBrXfYxRSZMDT/fO9NLX+hrxz4RiUrXmFm8I4vhayjStWl04Bbqr2INHfvUUDmkJptr5kHXVztwJhsOxXZCAscRduzjIpR5/vnoo1DtzzT2UEArbLoQYR1Y4YE7bqiWXIFhbcQS+1sbWi3tSZA2C6SoZAOC7Xs3pC9xKxjJ200OfES8YVIDS1A19LBivsGw3o6lj5Y1NQwMIeK4ajitARUnZq0Sp7i31C7kzPtw/rY1fF2gsUMm7mI781md97JN1pWdzJMCAnDn/Oh8qGb+oao4F2WRtHCquRh6us+B8tYy9nHzpHSWs48/EaPlKCovlofmy2anpb1MXkFQjHmwDAkU465NGmQL6cc3PkXPL66sGYMUojSA682Uu2UTXUt+aY67vTTSb6ZF/orjFmPd5HJ7DhaVxkeLCKA49Pay7KprRUjqPwXn/bljnk4wdLM2GbNxKd91rba5qaxsma67t8Be4Z/mlvU+rmDGdpmS0wSTpKSwp6EBNbnw4/0wjtEDSP8ikuDM3YOydJdgXJp2E3swMu22fwz4IdgbHmDHpbwSSub0UGuRY=
  password:
    secure: sEt7Tns028Qk7pyzUSPNR3RtxfNU1PhLLONy1DDPuXTKHP/hQnToM6xfNo5joY+uUwZploFN53ZMKRjU5qjG2CfFbUxnPFrdFZMG/smQGstPvqtDDZMsD36Hki5ma1izFAbLzjo2RJ/nwSr1/3cpaU01ACAmTuu/cUVKT4/PUxu7rZZdVz8y/FH+Psb5d7gIZNfrMDOJdFX4+GZ1aNHLekt19+636dB5p6OucAW0dx2ZzGnXOrcnnHAwZHuxiYG3DF6idpd0Uy5/y80Azmfclsbqy6DtBvrTV3KsCfA3j5tfXnbttCERcJIpf0aFa7WwrbxKENuAbu8lzEV+4JvevnKz2/lX10WWT73halaZGOfaX6L7p3nOrhOPGL5JFVSmWMQ7pHbL7CgTy64FqdLZ49XUTwINSmDZ9jV70Nhyj66KqMud9Z2WMt8A5szlfPrqLbBXBpr8l/rj6xL4r2hGwUEBpDdQ0jdcbu6zOvGPHkEj3iHQCK1zFXwh6Ym9NNUJDHVoF0Nuz4mYCPnXEOMnMXEtdASvMgsG5wv+y2wbg9gDCp+YHFLg3Mb/oujMvvuuBr7vf6oWHr8Dp+qwnECg4IHyk+xPo5qgjgqqGeJ0vC1RS2T9EJUBKrTEjg9sFsXhAVXDnoJnFzrcrc66gOykQBg2yz3N91+sK0nGcFIJS5g=
